id: IB1E0D059
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T21:42:55+00:00'
last_modified: '2022-06-08T13:15:11.771335+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1262
  title: ལུ་ཨི་པའི་དཀྱིལ་ཆོག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    233F:
      image_group_id: I1CZ1743
      title: Volume 1 of lu i pa'i dkyil chog
      total_pages: 20
      order: 1
      base_file: 233F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
