id: P007021
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:36:44.381367
source_metadata:
  id: bdr:W1CZ1262
  title: ལུ་ཨི་པའི་དཀྱིལ་ཆོག
  author: ''
  volumes:
    608615d6fdc047c59a7af22c61f6beb7:
      image_group_id: I1CZ1743
      title: Volume 1 of lu i pa'i dkyil chog
      volume_number: 1
      total_pages: 20
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
